[build]
  functions = "netlify/functions"

[functions]
  included_files = ["words/**"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
